name: Markdown
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.20
        with:
          template: markdown
          filename: README.md
          markdown_cache: .cache
          markdown: https://raw.githubusercontent.com/WayneHsu00/WayneHsu00/main/template.md
          config_output: markdown

          # Options
          user: WayneHsu00
          base: header, metadata, activity, community
          config_timezone: Asia/Shanghai
          repositories_skipped: WayneHsu00.github.io, WayneHsu00

          # plugin
          plugin_activity: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, fluent, gnuplot
          plugin_languages_skipped: waynehsu00.github.io, WayneHsu00

          plugin_rss: yes
          plugin_rss_source: https://waynehsu00.github.io/feed.xml
          plugin_rss_limit: 3

          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph

          # Token
          token: ${{ secrets.METRICS_TOKEN }}
